In [58]:
import pandas as pd

agua = pd.read_excel("Aguas_datos.xlsx")

In [59]:
agua.head()

   Tamano Hielo     Sabor  Score
0  grande   sin    kahlua    8.2
1  grande   con    kahlua    9.0
2   chica   sin    kahlua    7.0
3   chica   con    kahlua    7.5
4  grande   con  horchata   10.0

In [60]:
#quiero crear un nuevo dataframe con 0 o 1, dependiendo, por ejemplo en tamaño 1 es grande y 0 es chica, en hielo es 0 sin y 1 con, para sabor se crean dos columnas una para cada sabor, 0 si no esta 1 si si esta, y el score

df = pd.DataFrame()

df["Tamaño"] = agua["Tamano"].map ({"grande": 1, "chica": 0})
df["Hielo"] = agua["Hielo"].map ({"con": 1, "sin": 0})
df["kahlua"] = agua["Sabor"].map ({"kahlua": 1, "horchata": 0})
df["horchata"] = agua["Sabor"].map ({"horchata": 1, "kahlua": 0})    
df["Score"] = agua["Score"]

df.head()

   Tamaño  Hielo  kahlua  horchata  Score
0       1      0       1         0    8.2
1       1      1       1         0    9.0
2       0      0       1         0    7.0
3       0      1       1         0    7.5
4       1      1       0         1   10.0

In [64]:
#parte 2, ahora quiero sin = -1, con = 1, grande = -1, chica = 1 
df2 = pd.DataFrame()
df2["Tamaño"] = agua["Tamano"].map ({"grande": -1, "chica": 1})
df2["Hielo"] = agua["Hielo"].map ({"con": 1, "sin": -1})
df2["kahlua"] = agua["Sabor"].map ({"kahlua": 1, "horchata": 0})
df2["horchata"] = agua["Sabor"].map ({"horchata": 1, "kahlua": 0})
df2["Score"] = agua["Score"]

df2.head()

   Tamaño  Hielo  kahlua  horchata  Score
0      -1     -1       1         0    8.2
1      -1      1       1         0    9.0
2       1     -1       1         0    7.0
3       1      1       1         0    7.5
4      -1      1       0         1   10.0

In [65]:
#parte 3 = comparar betas de la parte 1 con la parte 2, para ver si el signo de las betas cambia o no, y si el valor absoluto de las betas cambia o no
import statsmodels.api as sm
X = df[["Tamaño", "Hielo", "kahlua", "horchata"]]
y = df["Score"]
X = sm.add_constant(X)
model = sm.OLS(y, X).fit()
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  Score   R-squared:                       0.837
Model:                            OLS   Adj. R-squared:                  0.714
Method:                 Least Squares   F-statistic:                     6.824
Date:                Mon, 09 Feb 2026   Prob (F-statistic):             0.0473
Time:                        17:55:35   Log-Likelihood:                -6.6425
No. Observations:                   8   AIC:                             21.29
Df Residuals:                       4   BIC:                             21.60
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          4.3000      0.320     13.417      0.000       3.410       5.190
Tamaño         2.4500      0.555      4.414      0.012       0.909       3.991
Hielo          0.5500      0.555      0.991      0.378      -0.991       2.091
kahlua         2.1250      0.320      6.631      0.003       1.235       3.015
horchata       2.1750      0.320      6.787      0.002       1.285       3.065
==============================================================================
Omnibus:                        7.172   Durbin-Watson:                   1.431
Prob(Omnibus):                  0.028   Jarque-Bera (JB):                1.242
Skew:                          -0.048   Prob(JB):                        0.537
Kurtosis:                       1.072   Cond. No.                     3.17e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.64e-32. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

c:\Users\jorgo\anaconda3\Lib\site-packages\scipy\stats\_axis_nan_policy.py:531: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  res = hypotest_fun_out(*samples, **kwds)

In [66]:
X = df2[["Tamaño", "Hielo", "kahlua", "horchata"]]
y = df2["Score"]
X = sm.add_constant(X)
model = sm.OLS(y, X).fit()
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  Score   R-squared:                       0.837
Model:                            OLS   Adj. R-squared:                  0.714
Method:                 Least Squares   F-statistic:                     6.824
Date:                Mon, 09 Feb 2026   Prob (F-statistic):             0.0473
Time:                        17:55:53   Log-Likelihood:                -6.6425
No. Observations:                   8   AIC:                             21.29
Df Residuals:                       4   BIC:                             21.60
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          5.3000      0.185     28.644      0.000       4.786       5.814
Tamaño        -1.2250      0.278     -4.414      0.012      -1.996      -0.454
Hielo          0.2750      0.278      0.991      0.378      -0.496       1.046
kahlua         2.6250      0.293      8.973      0.001       1.813       3.437
horchata       2.6750      0.293      9.143      0.001       1.863       3.487
==============================================================================
Omnibus:                        7.172   Durbin-Watson:                   1.431
Prob(Omnibus):                  0.028   Jarque-Bera (JB):                1.242
Skew:                          -0.048   Prob(JB):                        0.537
Kurtosis:                       1.072   Cond. No.                     2.70e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.64e-32. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

c:\Users\jorgo\anaconda3\Lib\site-packages\scipy\stats\_axis_nan_policy.py:531: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  res = hypotest_fun_out(*samples, **kwds)